#ifndef FSSH_REPLAY_H_
#define FSSH_REPLAY_H_

#include <cstddef>
#include <string>

/// @brief Aggregate error metrics for a fixed-nuclear-path FSSH replay.
struct FsshReplaySummary {
    std::size_t steps = 0;                 ///< Number of replayed electronic steps.
    std::size_t proposed_state_mismatches = 0; ///< ABACUS/PySCF proposed-hop disagreements.
    double max_hop_probability_error = 0.0; ///< Largest absolute probability difference.
    double max_pre_decoherence_error = 0.0; ///< Largest complex-amplitude error before damping.
    double max_post_decoherence_error = 0.0; ///< Largest complex-amplitude error after damping.
    double max_tau_error = 0.0;            ///< Largest finite decoherence-time difference.
    double max_damping_error = 0.0;        ///< Largest damping-factor difference.
};

/// @brief File-driven, fixed-nuclear-path interface to the ABACUS FSSH kernel.
/// @details The input is a text stream generated by the companion PySCF exporter.
/// It contains no orbital coefficients or electronic-structure instructions:
/// state energies, time-NAC, post-hop kinetic energy, random numbers and PySCF
/// reference observables are sufficient.  The interface is intentionally kept
/// separate from production MD so replay never launches an ABACUS SCF or TDDFT
/// calculation.
class FsshReplay {
public:
    /// @brief Run an externally supplied FSSH replay and write a per-step CSV comparison.
    /// @param input_path Path to a `FSSH_REPLAY_V1` or segmented `FSSH_REPLAY_V2` text stream.
    /// @param comparison_path Destination CSV path for ABACUS/PySCF diagnostics.
    /// @param summary_path Destination JSON path for aggregate diagnostics.
    /// @return Aggregate replay comparison metrics.
    /// @throw std::runtime_error for malformed input or an invalid FSSH state sequence.
    FsshReplaySummary run(const std::string& input_path,
                          const std::string& comparison_path,
                          const std::string& summary_path) const;
};

#endif  // FSSH_REPLAY_H_
