#include "fssh_replay.h"

#include "source_lcao/module_operator_lcao/fssh_driver.h"

#include <algorithm>
#include <cmath>
#include <complex>
#include <fstream>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

struct ReplayHeader {
    int nstates = 0;
    int nsteps = 0;
    double dt_au = 0.0;
    int initial_state = 0;
    bool decoherence = false;
    double alpha = 0.1;
    std::vector<std::complex<double>> initial_coefficients;
};

struct ReplayRecord {
    FsshReplayStepInput input;
    int reference_proposed_state = -1;
    std::vector<std::complex<double>> reference_before_decoherence;
    std::vector<std::complex<double>> reference_after_decoherence;
    std::vector<double> reference_probabilities;
    std::vector<double> reference_tau;
    std::vector<double> reference_damping;
};

/// @brief Read a required scalar replay-header field.
template <typename T>
void read_header_value(std::istream& stream, const char* expected_key, T& value) {
    std::string key;
    if (!(stream >> key >> value) || key != expected_key) {
        throw std::runtime_error(std::string("invalid FSSH replay header field: ") + expected_key);
    }
}

/// @brief Read one replay record generated by export_pyscf_fssh_replay.py.
bool read_record(std::istream& stream, int nstates, ReplayRecord& record) {
    int step = 0;
    if (!(stream >> step)) return false;
    if (!(stream >> record.input.active_state_before >> record.input.active_state_after
          >> record.reference_proposed_state >> record.input.random_number
          >> record.input.kinetic_energy)) {
        throw std::runtime_error("truncated FSSH replay record header");
    }

    record.input.energies.resize(nstates);
    for (double& energy : record.input.energies) {
        if (!(stream >> energy)) throw std::runtime_error("truncated FSSH replay energies");
    }

    record.input.time_nac.create(nstates, nstates);
    for (int i = 0; i < nstates; ++i) {
        for (int j = 0; j < nstates; ++j) {
            double value = 0.0;
            if (!(stream >> value)) throw std::runtime_error("truncated FSSH replay time-NAC");
            record.input.time_nac(i, j) = std::complex<double>(value, 0.0);
        }
    }

    auto read_complex_vector = [&stream, nstates](std::vector<std::complex<double>>& values,
                                                   const char* description) {
        values.resize(nstates);
        for (auto& value : values) {
            double real = 0.0;
            double imag = 0.0;
            if (!(stream >> real >> imag)) {
                throw std::runtime_error(std::string("truncated FSSH replay ") + description);
            }
            value = std::complex<double>(real, imag);
        }
    };
    auto read_real_vector = [&stream, nstates](std::vector<double>& values, const char* description) {
        values.resize(nstates);
        for (double& value : values) {
            std::string token;
            if (!(stream >> token)) throw std::runtime_error(std::string("truncated FSSH replay ") + description);
            try {
                value = std::stod(token);
            } catch (const std::exception&) {
                throw std::runtime_error(std::string("invalid floating-point value in FSSH replay ") + description);
            }
        }
    };

    read_complex_vector(record.reference_before_decoherence, "pre-decoherence coefficients");
    read_complex_vector(record.reference_after_decoherence, "post-decoherence coefficients");
    read_real_vector(record.reference_probabilities, "hop probabilities");
    read_real_vector(record.reference_tau, "decoherence times");
    read_real_vector(record.reference_damping, "decoherence damping factors");
    return true;
}

double finite_absolute_error(double lhs, double rhs) {
    if (!std::isfinite(lhs) && !std::isfinite(rhs)) return 0.0;
    if (!std::isfinite(lhs) || !std::isfinite(rhs)) return std::numeric_limits<double>::infinity();
    return std::abs(lhs - rhs);
}

}  // namespace

FsshReplaySummary FsshReplay::run(const std::string& input_path,
                                   const std::string& comparison_path,
                                   const std::string& summary_path) const {
    std::ifstream input(input_path);
    if (!input.is_open()) throw std::runtime_error("cannot open FSSH replay input: " + input_path);

    std::string version;
    if (!(input >> version) || (version != "FSSH_REPLAY_V1" && version != "FSSH_REPLAY_V2")) {
        throw std::runtime_error("unsupported FSSH replay format");
    }
    const bool has_segment_initial_state = version == "FSSH_REPLAY_V2";

    ReplayHeader header;
    int decoherence_flag = 0;
    read_header_value(input, "nstates", header.nstates);
    read_header_value(input, "nsteps", header.nsteps);
    read_header_value(input, "dt_au", header.dt_au);
    read_header_value(input, "initial_state", header.initial_state);
    read_header_value(input, "decoherence", decoherence_flag);
    read_header_value(input, "alpha", header.alpha);
    header.decoherence = decoherence_flag != 0;
    if (header.nstates < 2 || header.nsteps < 1 || header.dt_au <= 0.0
        || header.initial_state < 0 || header.initial_state >= header.nstates) {
        throw std::runtime_error("invalid FSSH replay header values");
    }
    if (std::abs(header.alpha - 0.1) > 1.0e-14) {
        throw std::runtime_error("current ABACUS replay supports the production alpha = 0.1 only");
    }
    if (has_segment_initial_state) {
        std::string initial_coefficients_tag;
        if (!(input >> initial_coefficients_tag) || initial_coefficients_tag != "initial_coefficients") {
            throw std::runtime_error("missing FSSH replay initial coefficients");
        }
        header.initial_coefficients.resize(header.nstates);
        for (auto& coefficient : header.initial_coefficients) {
            double real = 0.0;
            double imag = 0.0;
            if (!(input >> real >> imag)) {
                throw std::runtime_error("truncated FSSH replay initial coefficients");
            }
            coefficient = {real, imag};
        }
    }
    std::string data_tag;
    if (!(input >> data_tag) || data_tag != "data") {
        throw std::runtime_error("missing FSSH replay data marker");
    }

    std::ofstream comparison(comparison_path);
    if (!comparison.is_open()) throw std::runtime_error("cannot open FSSH replay comparison output: " + comparison_path);
    comparison << "step,active_before,active_after_reference,proposed_reference,proposed_abacus";
    for (int state = 0; state < header.nstates; ++state) comparison << ",probability_error_" << state;
    for (int state = 0; state < header.nstates; ++state) comparison << ",pre_coefficient_error_" << state;
    for (int state = 0; state < header.nstates; ++state) comparison << ",post_coefficient_error_" << state;
    for (int state = 0; state < header.nstates; ++state) comparison << ",tau_error_" << state;
    for (int state = 0; state < header.nstates; ++state) comparison << ",damping_error_" << state;
    comparison << '\n' << std::setprecision(17);

    FsshDriver driver;
    driver.init(0, header.nstates, header.dt_au, header.initial_state, 0, 0,
                header.decoherence, 0U);
    if (has_segment_initial_state) {
        driver.set_replay_state(header.initial_state, header.initial_coefficients);
    }

    FsshReplaySummary summary;
    for (int step = 1; step <= header.nsteps; ++step) {
        ReplayRecord record;
        if (!read_record(input, header.nstates, record)) {
            throw std::runtime_error("FSSH replay input ended before the declared number of steps");
        }
        const FsshReplayStepResult result = driver.run_step_replay(record.input);
        comparison << step << ',' << result.active_state_before << ',' << result.active_state_after
                   << ',' << record.reference_proposed_state << ',' << result.proposed_state;
        const int expected_proposal = record.reference_proposed_state >= 0
                                          ? record.reference_proposed_state
                                          : result.active_state_before;
        if (result.proposed_state != expected_proposal) ++summary.proposed_state_mismatches;

        for (int state = 0; state < header.nstates; ++state) {
            const double error = finite_absolute_error(result.hopping_probabilities[state],
                                                       record.reference_probabilities[state]);
            summary.max_hop_probability_error = std::max(summary.max_hop_probability_error, error);
            comparison << ',' << error;
        }
        for (int state = 0; state < header.nstates; ++state) {
            const double error = std::abs(result.coefficients_before_decoherence[state]
                                          - record.reference_before_decoherence[state]);
            summary.max_pre_decoherence_error = std::max(summary.max_pre_decoherence_error, error);
            comparison << ',' << error;
        }
        for (int state = 0; state < header.nstates; ++state) {
            const double error = std::abs(result.coefficients_after_decoherence[state]
                                          - record.reference_after_decoherence[state]);
            summary.max_post_decoherence_error = std::max(summary.max_post_decoherence_error, error);
            comparison << ',' << error;
        }
        for (int state = 0; state < header.nstates; ++state) {
            const double error = finite_absolute_error(result.decoherence_tau[state], record.reference_tau[state]);
            summary.max_tau_error = std::max(summary.max_tau_error, error);
            comparison << ',' << error;
        }
        for (int state = 0; state < header.nstates; ++state) {
            const double error = finite_absolute_error(result.decoherence_damping[state],
                                                       record.reference_damping[state]);
            summary.max_damping_error = std::max(summary.max_damping_error, error);
            comparison << ',' << error;
        }
        comparison << '\n';
        ++summary.steps;
    }

    std::ofstream summary_output(summary_path);
    if (!summary_output.is_open()) throw std::runtime_error("cannot open FSSH replay summary output: " + summary_path);
    summary_output << std::setprecision(17)
                   << "{\n"
                   << "  \"steps\": " << summary.steps << ",\n"
                   << "  \"proposed_state_mismatches\": " << summary.proposed_state_mismatches << ",\n"
                   << "  \"max_hop_probability_error\": " << summary.max_hop_probability_error << ",\n"
                   << "  \"max_pre_decoherence_error\": " << summary.max_pre_decoherence_error << ",\n"
                   << "  \"max_post_decoherence_error\": " << summary.max_post_decoherence_error << ",\n"
                   << "  \"max_tau_error\": " << summary.max_tau_error << ",\n"
                   << "  \"max_damping_error\": " << summary.max_damping_error << "\n"
                   << "}\n";
    return summary;
}
